### PR TITLE
Splitting XML into files

### PR DESCRIPTION
**Pull request by themanyfaceddemon**
I immediately created a PR to keep a list of the changes I made while working on it.

# What has changed?
## General changes
- Split everything into files and try to extract all common features from similar objects to reduce xml code
- Removed comments for obvious blocks of code such as:
```diff
-<!-- Remove the item when fully used -->
 <StatusEffect type="OnBroken" target="This">
     <Remove/>
 </StatusEffect>
```

## Defibrillators
- A separate parent has been made to shorten the code

## Implants
- A separate parent has been made to shorten the code

## Instruments
- The following items have a disassembly time of 5: `tweezers`, `surgerysaw`, `surgicaldrill`, `advretractors`, `advhemostat`

## Scalpels
- A separate parent has been made to shorten the code
- `organscalpel_brain` now has the same chance of appearing in toxcontainer as normal organ scalpels: 20%

## Limbs
- A separate parent has been made to shorten the code

## Organs
- A separate parent has been made to shorten the code

### CODE REVIEW

**Comment by themanyfaceddemon** [comment]
img
💀

**Comment by themanyfaceddemon** [comment]
Why... Okay, I'll figure it out later

**Comment by themanyfaceddemon** [comment]
@OlegBSTU It's ready.
If you're going to merge - request via squish

**Comment by themanyfaceddemon** [comment]
If necessary, I can completely remove "base_.*" items

**Comment by themanyfaceddemon** [comment]
Mmm... In fact, you can get rid of the item placeholders and make every other item with a change in the properties of the remaining ones. I'm thinking about whether to remake it like this.

**Comment by themanyfaceddemon** [comment]
> Todo doesn't seem to be complete, I suspect some of them lost in the item xml code / it wasn't typed as "TODO:" to detect it

I'll check again today

**Comment by themanyfaceddemon** [comment]
done

**Comment by OlegBSTU** [comment]
I disagree with base_ items, in this case they do not serve anything, if even something, in my opinion.

**Comment by OlegBSTU** [comment]
I disagree with disassembly times, they are too small.

**Comment by themanyfaceddemon** [comment]
Okay, I'll remove variantof from everything where I added it as soon as I have time

**Comment by themanyfaceddemon** [comment]
@OlegBSTU done

**Comment by OlegBSTU** [comment]
> I disagree with disassembly times, they are too small.

I feel like 5 seconds is actually what deconstuctor time defaults to if not defined. So other than that, looks good, merged with commit squash. Thanks for contribution!

**Pull request merged**
