### PR TITLE
Removing the crutch with the creation of objects with sounds

### PR DESCRIPTION
**Pull request by themanyfaceddemon**
This pull request removes SFX completely, replacing it with sound creation via lua.

HF.PlaySound(soundTag, position, range, volume)
Plays a sound at a specified position in the game world, with optional range and volume.

Parameters:
- soundTag (string): A string indicating the tag identifier.
- position (Vector2): The position in the game world where the sound will originate.
- range (number, optional): The radius in which the sound will be audible. By default it uses the value from the xml file.
- volume (number, optional): The volume multiplier for the sound (from 0.0 to 1.0). By default it uses the value from the xml file.

Usage:
```lua
HF.PlaySound(soundTag, position)           -- Plays sound at full volume and default range.
HF.PlaySound(soundTag, position, 500)      -- Plays sound with default volume and 500 range.
HF.PlaySound(soundTag, position, 500, 0.5) -- Plays sound with 50% volume and 500 range.
```

Squish merge please!!!
I'm too lazy to name commits normally that way, but I wanted to have at least some order in the repo

### CODE REVIEW

**Comment by themanyfaceddemon** [comment]
@OlegBSTU, It should actually work
And can you give the ability to request a review? :slugevil:

**Comment by Ydrec** [comment]
Why werent these just defined in respective item xml what the actual fuck manna spawned separate items to make sounds

**Comment by themanyfaceddemon** [comment]
idn

**Comment by Zipliks** [comment]
`PlaySound()` is a client-side method, so it won't work for nearby players.

**Comment by themanyfaceddemon** [comment]
:skull:

**Comment by themanyfaceddemon** [comment]
In short, my brain is too smooth to solve this normally. I did not find how to normally call the sound through Lua from the server to the client

**Comment by Nebual** [comment]
@themanyfaceddemon Indeed I don't see an existing generic way to trigger SoundPlay from the server, but I think you can use a custom network message to do that, like so (untested):
```
function HF.PlaySound(soundTag, position, range, volume)
    if SERVER then
        local msg = Networking.Start("HF.PlaySound")
        msg.WriteString(soundTag)
        msg.WriteSingle(position.X)
        msg.WriteSingle(position.Y)
        msg.WriteSingle(range)
        msg.WriteSingle(volume)
        Networking.Send(msg) -- send to all clients
    else
        SoundPlayer.PlaySound(soundTag, position, volume, range)
    end
end

if CLIENT then
    Networking.Receive("HF.PlaySound", function(msg)
        NTConfig.ReceiveConfig(msg)
        local soundTag = msg.ReadString()
        local position = Vector2(msg.ReadSingle(), msg.ReadSingle())
        local range = msg.ReadSingle()
        local volume = msg.ReadSingle()
        SoundPlayer.PlaySound(soundTag, position, volume, range)
    end)
end
```

**Comment by themanyfaceddemon** [comment]
> @themanyfaceddemon Indeed I don't see an existing generic way to trigger SoundPlay from the server, but I think you can use a custom network message to do that, like so (untested):
> 
> ```
> function HF.PlaySound(soundTag, position, range, volume)
>     if SERVER then
>         local msg = Networking.Start("HF.PlaySound")
>         msg.WriteString(soundTag)
>         msg.WriteSingle(position.X)
>         msg.WriteSingle(position.Y)
>         msg.WriteSingle(range)
>         msg.WriteSingle(volume)
>         Networking.Send(msg) -- send to all clients
>     else
>         SoundPlayer.PlaySound(soundTag, position, volume, range)
>     end
> end
> 
> if CLIENT then
>     Networking.Receive("HF.PlaySound", function(msg)
>         NTConfig.ReceiveConfig(msg)
>         local soundTag = msg.ReadString()
>         local position = Vector2(msg.ReadSingle(), msg.ReadSingle())
>         local range = msg.ReadSingle()
>         local volume = msg.ReadSingle()
>         SoundPlayer.PlaySound(soundTag, position, volume, range)
>     end)
> end
> ```

I also think that something separate needs to be built, but I'm thinking of throwing it into Lua right away so that everyone can use it, and not build porn. At the same time, Evil Factory can hit me on the head if something is wrong

**Pull request closed without merging**
